# Generated by Django 4.2.1 on 2023-07-22 00:42

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=dashboard.models.generate_coupon_code, max_length=50, unique=True)),
                ('discount', models.PositiveIntegerField()),
                ('min_amount', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('uses', models.IntegerField(default=1)),
                ('active_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
