# Generated by Django 4.2.1 on 2023-07-22 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_alter_coupon_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='apply_coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uses', models.PositiveIntegerField(default=0)),
                ('coupon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.coupon')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
