# Generated by Django 4.2.1 on 2023-07-22 04:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_apply_coupon'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='apply_coupon',
            new_name='Verify_coupon',
        ),
    ]
