# Generated by Django 4.2.1 on 2023-07-31 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_carouselitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselitem',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
