# Generated by Django 4.2.1 on 2023-08-04 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_carouselitem_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='image',
            field=models.ImageField(upload_to='Carousel/'),
        ),
        migrations.AlterField(
            model_name='verify_coupon',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.coupon'),
        ),
    ]
