# Generated by Django 4.2.1 on 2023-05-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_accounts',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
