# Generated by Django 4.2.1 on 2023-05-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_accounts_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_accounts',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
