# Generated by Django 4.2.1 on 2023-05-15 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_accounts_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_accounts',
            name='otp',
        ),
    ]
