# Generated by Django 4.2.1 on 2023-05-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_accounts_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_accounts',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
