# Generated by Django 4.2.1 on 2023-05-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_accounts_otp_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_accounts',
            name='otp_verified',
        ),
        migrations.AddField(
            model_name='user_accounts',
            name='account_status',
            field=models.CharField(blank=True, default='active', max_length=10),
        ),
    ]
