# Generated by Django 4.2.1 on 2023-07-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
