# Generated by Django 4.2.1 on 2023-07-29 01:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_accounts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
