# Generated by Django 4.2.1 on 2023-07-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_deliverd_at_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='coupon_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='coupon_discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='coupon_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='spike_discount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='spike_use',
            field=models.BooleanField(default=False),
        ),
    ]
