# Generated by Django 4.2.1 on 2023-07-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_payment_coupon_code_payment_coupon_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Confirmed', 'Confirmed'), ('shipping', 'shipping'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Return initiated', 'Return initiated'), ('Returned', 'Returned')], default='New', max_length=50),
        ),
    ]
