# Generated by Django 4.2.1 on 2023-05-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_table',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
