# Generated by Django 4.2.1 on 2023-05-23 17:48

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_table_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_item',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product_item',
            name='images',
        ),
        migrations.AlterField(
            model_name='products_table',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.generate_upload_path),
        ),
    ]
