# Generated by Django 4.2.1 on 2023-05-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_images_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_item',
            options={'verbose_name_plural': 'Products_varients'},
        ),
        migrations.AlterUniqueTogether(
            name='product_item',
            unique_together={('product', 'size')},
        ),
    ]
