# Generated by Django 4.2.1 on 2023-06-12 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_tags_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductTag',
            new_name='P_tags',
        ),
    ]
