# Generated by Django 4.2.1 on 2023-06-13 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_productclassification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productclassification',
            name='product',
        ),
    ]
