# Generated by Django 4.2.1 on 2023-06-13 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_productclassification_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='classfiedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productclassification')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products_table')),
            ],
            options={
                'unique_together': {('product', 'classification')},
            },
        ),
    ]
