# Generated by Django 4.2.1 on 2023-06-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_product_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='classfiedproducts',
            name='offer',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product_item',
            name='offer_price',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
