# Generated by Django 4.2.1 on 2023-06-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_classfiedproducts_offer_product_item_offer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_item',
            name='quantity',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
