# Generated by Django 4.2.1 on 2023-06-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_product_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_item',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
