# Generated by Django 4.2.1 on 2023-06-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_product_item_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='classfiedproducts',
            name='offer',
            field=models.PositiveIntegerField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_item',
            name='offer_price',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
