# Generated by Django 4.2.1 on 2023-06-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_classfiedproducts_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_item',
            name='offer_price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
